# Generated by Django 2.1.7 on 2019-02-13 11:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question',
                 models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('test',
                 models.CharField(choices=[('atleast', 'At least'), ('nomore', 'No more than'), ('never', 'Never')],
                                  max_length=10)),
                ('frequency', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                                           django.core.validators.MaxValueValidator(
                                                                               7)])),
                ('cheat', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3),
                                                                       django.core.validators.MaxValueValidator(14)])),
                ('style', models.CharField(choices=[('yesno', 'Yes/No'), ('likert', 'Likert')], max_length=10)),
                ('startDate', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
