# Generated by Django 2.1.7 on 2019-02-13 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('question', 'owner')},
        ),
    ]
