# Generated by Django 2.1.7 on 2019-02-13 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0003_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
