# Generated by Django 2.1.7 on 2019-02-17 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0004_auto_20190213_2203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('goal', 'date')},
        ),
    ]
