# Generated by Django 2.1.7 on 2019-02-18 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0005_auto_20190217_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='cheat',
            field=models.PositiveSmallIntegerField(blank=True, null=True,
                                                   validators=[django.core.validators.MinValueValidator(3),
                                                               django.core.validators.MaxValueValidator(14)]),
        ),
    ]
