# Generated by Django 2.1.7 on 2019-02-19 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0006_auto_20190218_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='question',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
