# Generated by Django 2.1.7 on 2019-02-13 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('name', 'user')},
        ),
    ]
