# Generated by Django 2.1.7 on 2019-02-13 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0004_auto_20190213_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='healthIndex',
            new_name='health_index',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='isArchived',
            new_name='is_archived',
        ),
    ]
