# Generated by Django 2.1.7 on 2019-02-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0005_auto_20190213_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
