# Generated by Django 2.1.7 on 2019-02-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0006_auto_20190214_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumption',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='food',
            name='icon',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
